/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**sudo update-alternatives --config java
 *
 * @author 1hunt
 */
public class GUI extends javax.swing.JFrame {

        // sets buttons as blank to start, needed spaces as no values messes up
        // formatting
        String option1 = "  ";
        String option2 = "  ";
        String option3 = "  ";
        String option4 = "  ";

        // sets numbers as 0 to start
        int correctCount = 0;
        int questionCount = 0;
        int questionsLeft = 0; // change to inputted amount of questions on start

        // declaring variables for later
        String correct;
        List<Integer> correctCoordinates;
        String correctImage;

        /**
         * Creates new form GUI
         */
        public GUI() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();

                // making spinner range
                // https://www.tutorialspoint.com/how-to-limit-the-values-in-a-number-jspinner-component-with-java
                SpinnerModel value = new SpinnerNumberModel(10, 1, 100000, 1);
                jSpinner1 = new javax.swing.JSpinner(value);
                // turning off spinner typing ability
                // https://stackoverflow.com/questions/6904326/how-do-i-disable-keyboard-and-mouse-entry-for-a-jspinner
                jSpinner1.setEnabled(true);
                if (jSpinner1.getEditor() instanceof JSpinner.DefaultEditor) {
                        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) jSpinner1.getEditor();
                        editor.getTextField().setEnabled(true);
                        editor.getTextField().setEditable(false);
                }

                jLabel4 = new javax.swing.JLabel();
                jButton5 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setIcon(new javax.swing.ImageIcon(correctImage)); // NOI18N
                jLabel1.setToolTipText("");

                jButton1.setText(option1);

                jButton2.setText(option2);

                jButton3.setText(option3);

                jButton4.setText(option4);

                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jLabel2.setText("Score:" + correctCount + "/" + questionCount); // sets score to questions correct over
                                                                                // questions answered

                jLabel3.setText("Remaining:" + questionsLeft); // sets remaining to questions left to answer

                jLabel4.setText("Number of Questions:");

                jButton5.setText("Start");
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel2)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabel4)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel3)
                                                                                                .addGap(375, 400,
                                                                                                                Short.MAX_VALUE)))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jButton5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                84,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jSpinner1))
                                                                .addContainerGap())
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(jButton1)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(jButton2))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                18,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jLabel1)
                                                                                                                                .addGap(19, 19, 19)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jButton3)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jButton4)))
                                                                .addGap(191, 191, 191)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jSpinner1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel4)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jButton5))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                22,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                182,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton1)
                                                                                .addComponent(jButton2))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton3)
                                                                                .addComponent(jButton4))
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                afterQuestion(option1); // afterQuestion takes in option held by button to check for correctness
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
                afterQuestion(option2);
        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
                afterQuestion(option3);
        }

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
                afterQuestion(option4);
        }

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { // resets metrics when pressed and uses
                                                                               // spinner for amount of questions to ask
                correctCount = 0;
                questionCount = 0;
                questionsLeft = (int) jSpinner1.getValue(); // cast was quick fix
                jLabel3.setText("Remaining:" + questionsLeft);

                generateValues();
                update();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new GUI().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JSpinner jSpinner1;
        // End of variables declaration

        /**
         * Carries out scoring, generating new questions, and disallowing use of buttons
         * when they are blank, meant for option buttons
         * 
         * @param option
         */
        private void afterQuestion(String option) {
                if (option.equals(correct)) {
                        correctCount++;
                }
                if (!option.equals("  ")) {
                        questionsLeft = questionsLeft - 1;
                        questionCount = questionCount + 1;
                        if (questionsLeft == 0) {
                                option1 = "  ";
                                option2 = "  ";
                                option3 = "  ";
                                option4 = "  ";
                                correctImage = "";

                        } else {
                                generateValues();
                        }
                        update();
                }
        }

        /**
         * generates new option, correct answer, and image values
         */
        private void generateValues() {
                ArrayList<String> options = DataReader.getOptions(); // uses methods from DataReader and sets them to
                                                                     // GUI Variables

                option1 = options.get(0);
                option2 = options.get(1);
                option3 = options.get(2);
                option4 = options.get(3);

                correct = DataReader.getCorrect(options);
                correctCoordinates = DataReader.getPosition(correct);
                correctImage = SetData.getImageFolder() + DataReader.getValue(1, correctCoordinates.get(1)) + ".jpg";
        }

        /**
         * updates all variable aspects of GUI
         */
        private void update() {
                jButton1.setText(option1);
                jButton2.setText(option2);
                jButton3.setText(option3);
                jButton4.setText(option4);
                jLabel1.setIcon(new javax.swing.ImageIcon(correctImage));
                jLabel2.setText("Score:" + correctCount + "/" + questionCount);
                jLabel3.setText("Remaining:" + questionsLeft);
        }
}
